### ISSUE TITLE
AttributeError: 'Battery' object has no attribute 'charge_now'

### ISSUE THREAD

**Issue by monarc99** [Haptein/powerplan#8]
**Description**
After the update to newest git version, i get the error on my desktop system (no battery):

sudo powerplan --status
Traceback (most recent call last):
  File "/usr/bin/powerplan", line 157, in <module>
    main_loop(monitor_mode, system=system)
  File "/usr/bin/powerplan", line 51, in main_loop
    status = systemstatus.StatusMonitor(system, profiles)
  File "/opt/powerplan/src/systemstatus.py", line 247, in __init__
    super().__init__(system, profiles, fields)
  File "/opt/powerplan/src/systemstatus.py", line 92, in __init__
    self.field_methods = self._get_field_methods(fields=fields, custom_fields=custom_fields)
  File "/opt/powerplan/src/systemstatus.py", line 127, in _get_field_methods
    battery_charge_now=(self.battery.charge_now, {}),
AttributeError: 'Battery' object has no attribute 'charge_now'

**Comment by Haptein** [comment]
This should be fixed :+1: This is a good reminder to implement some automatic tests (which the new changes now allow).

**Comment by monarc99** [comment]
yes, is fixed :+1:
